### ISSUE TITLE
Expanded boilerplate templates similar to Breeze?

### ISSUE THREAD

**Issue by CitizenBeta** [clarity-digital/nextjs-jwt-app-router#7]
Hey! Assuming you're using this for production purposes, do you have any base templates for the login pages, notifications, that kind of thing similar to Breeze? The next step for me is to create them for my project but it would save a lot of time (similar to Breeze) if we had them added to the project. I know for boilerplates we want to prevent bloat but I dont think that it would be excessive to have.

**Comment by semammerlaan** [comment]
We created this boilerplate with minimal styling because every project has its own styling. You are free to customise it anyway you want, perhaps a fork would be the best option here?
