### ISSUE TITLE
[Meta] Are the authors using this project?

### ISSUE THREAD

**Issue by CitizenBeta** [clarity-digital/nextjs-jwt-app-router#9]
Hey Avocado Media folks, before I commit to using this and making contributions, I just want to make sure that you guys are actually using the repo for production purposes and have intent to grow and maintain it. It's a boilerplate, so I fully understand that this isn't a project that needs frequent updates, etc, but the pull request I just put through is a fix to a basic issue that would be preventing anyone from using the product all. I'm happy to fix it and make contributions, but if original authors of any project aren't using the project, it's probably not a good sign long-term. If you could provide clarity that would be greatly appreciated!

**Comment by semammerlaan** [comment]
Hi @CitizenBeta, we definitely appreciate any contributions, that's why we made it open-source. We use this boilerplate in production, however there might be some changes/additions done depending on the project 😃
